#ifndef EMOJI_H
#define EMOJI_H

typedef struct {
    const char *shortcode;
    const char *unicode;
} EmojiMapping;

/* Common emoji mappings */
static const EmojiMapping emoji_map[] = {
    /* Smileys & Emotion */
    {":grinning:", "😀"}, {":smiley:", "😃"}, {":smile:", "😄"}, {":grin:", "😁"},
    {":laughing:", "😆"}, {":sweat_smile:", "😅"}, {":joy:", "😂"}, {":rofl:", "🤣"},
    {":relaxed:", "☺️"}, {":blush:", "😊"}, {":innocent:", "😇"}, {":wink:", "😉"},
    {":heart_eyes:", "😍"}, {":kissing_heart:", "😘"}, {":kissing:", "😗"},
    {":smiling_face_with_tear:", "🥲"}, {":yum:", "😋"}, {":stuck_out_tongue:", "😛"},
    {":stuck_out_tongue_winking_eye:", "😜"}, {":stuck_out_tongue_closed_eyes:", "😝"},
    {":neutral_face:", "😐"}, {":expressionless:", "😑"}, {":no_mouth:", "😶"},
    {":smirk:", "😏"}, {":unamused:", "😒"}, {":grimacing:", "😬"},
    {":lying_face:", "🤥"}, {":relieved:", "😌"}, {":pensive:", "😔"},
    {":sleepy:", "😪"}, {":drooling_face:", "🤤"}, {":sleeping:", "😴"},
    {":mask:", "😷"}, {":face_with_thermometer:", "🤒"}, {":sneezing_face:", "🤧"},
    {":dizzy_face:", "😵"}, {":exploding_head:", "🤯"}, {":sunglasses:", "😎"},
    {":nerd_face:", "🤓"}, {":thinking:", "🤔"}, {":confused:", "😕"},
    {":slightly_frowning_face:", "🙁"}, {":frowning_face:", "☹️"}, {":persevere:", "😣"},
    {":confounded:", "😖"}, {":tired_face:", "😫"}, {":weary:", "😩"},
    {":cry:", "😢"}, {":sob:", "😭"}, {":triumph:", "😤"}, {":angry:", "😠"},
    {":rage:", "😡"}, {":scream:", "😱"}, {":fearful:", "😨"}, {":cold_sweat:", "😰"},
    {":disappointed_relieved:", "😥"}, {":sweat:", "😓"}, {":hugging_face:", "🤗"},
    {":star_struck:", "🤩"}, {":partying_face:", "🥳"}, {":woozy_face:", "🥴"},
    {":pleading_face:", "🥺"}, {":flushed:", "😳"}, {":zany_face:", "🤪"},
    {":shushing_face:", "🤫"}, {":raised_eyebrow:", "🤨"}, {":face_with_monocle:", "🧐"},

    /* Hearts */
    {":heart:", "❤️"}, {":orange_heart:", "🧡"}, {":yellow_heart:", "💛"},
    {":green_heart:", "💚"}, {":blue_heart:", "💙"}, {":purple_heart:", "💜"},
    {":black_heart:", "🖤"}, {":white_heart:", "🤍"}, {":brown_heart:", "🤎"},
    {":sparkling_heart:", "💖"}, {":heartpulse:", "💗"}, {":heartbeat:", "💓"},
    {":revolving_hearts:", "💞"}, {":two_hearts:", "💕"}, {":broken_heart:", "💔"},

    /* Hand gestures */
    {":wave:", "👋"}, {":raised_hand:", "✋"}, {":hand:", "✋"}, {":ok_hand:", "👌"},
    {":thumbsup:", "👍"}, {":thumbsdown:", "👎"}, {":fist:", "✊"},
    {":facepunch:", "👊"}, {":punch:", "👊"}, {":left_facing_fist:", "🤛"},
    {":right_facing_fist:", "🤜"}, {":clap:", "👏"}, {":raised_hands:", "🙌"},
    {":open_hands:", "👐"}, {":palms_up_together:", "🤲"}, {":handshake:", "🤝"},
    {":pray:", "🙏"}, {":writing_hand:", "✍️"}, {":nail_care:", "💅"},
    {":muscle:", "💪"}, {":point_left:", "👈"}, {":point_right:", "👉"},
    {":point_up_2:", "👆"}, {":point_down:", "👇"}, {":v:", "✌️"},
    {":crossed_fingers:", "🤞"}, {":metal:", "🤘"}, {":call_me_hand:", "🤙"},

    /* People */
    {":baby:", "👶"}, {":child:", "🧒"}, {":boy:", "👦"}, {":girl:", "👧"},
    {":adult:", "🧑"}, {":man:", "👨"}, {":woman:", "👩"}, {":older_adult:", "🧓"},
    {":older_man:", "👴"}, {":older_woman:", "👵"}, {":person_frowning:", "🙍"},
    {":person_with_pouting_face:", "🙎"}, {":no_good:", "🙅"}, {":ok_woman:", "🙆"},
    {":tipping_hand_woman:", "💁"}, {":raising_hand:", "🙋"}, {":bow:", "🙇"},
    {":facepalm:", "🤦"}, {":shrug:", "🤷"}, {":man_health_worker:", "👨‍⚕️"},
    {":woman_health_worker:", "👩‍⚕️"}, {":man_student:", "👨‍🎓"},
    {":woman_student:", "👩‍🎓"}, {":man_teacher:", "👨‍🏫"},
    {":woman_teacher:", "👩‍🏫"}, {":man_technologist:", "👨‍💻"},
    {":woman_technologist:", "👩‍💻"}, {":technologist:", "🧑‍💻"},

    /* Animals & Nature */
    {":dog:", "🐶"}, {":cat:", "🐱"}, {":mouse:", "🐭"}, {":hamster:", "🐹"},
    {":rabbit:", "🐰"}, {":fox_face:", "🦊"}, {":bear:", "🐻"}, {":panda_face:", "🐼"},
    {":koala:", "🐨"}, {":tiger:", "🐯"}, {":lion:", "🦁"}, {":cow:", "🐮"},
    {":pig:", "🐷"}, {":frog:", "🐸"}, {":monkey_face:", "🐵"}, {":see_no_evil:", "🙈"},
    {":hear_no_evil:", "🙉"}, {":speak_no_evil:", "🙊"}, {":monkey:", "🐒"},
    {":chicken:", "🐔"}, {":penguin:", "🐧"}, {":bird:", "🐦"}, {":baby_chick:", "🐤"},
    {":hatching_chick:", "🐣"}, {":dragon:", "🐉"}, {":unicorn:", "🦄"},
    {":bee:", "🐝"}, {":bug:", "🐛"}, {":butterfly:", "🦋"}, {":snail:", "🐌"},
    {":shell:", "🐚"}, {":octopus:", "🐙"}, {":fish:", "🐟"}, {":dolphin:", "🐬"},
    {":whale:", "🐳"}, {":shark:", "🦈"}, {":turtle:", "🐢"}, {":snake:", "🐍"},
    {":dragon_face:", "🐲"}, {":cactus:", "🌵"}, {":christmas_tree:", "🎄"},
    {":evergreen_tree:", "🌲"}, {":deciduous_tree:", "🌳"}, {":palm_tree:", "🌴"},
    {":seedling:", "🌱"}, {":herb:", "🌿"}, {":shamrock:", "☘️"}, {":four_leaf_clover:", "🍀"},
    {":maple_leaf:", "🍁"}, {":fallen_leaf:", "🍂"}, {":leaves:", "🍃"},
    {":mushroom:", "🍄"}, {":ear_of_rice:", "🌾"}, {":bouquet:", "💐"},
    {":tulip:", "🌷"}, {":rose:", "🌹"}, {":hibiscus:", "🌺"}, {":sunflower:", "🌻"},
    {":blossom:", "🌼"}, {":cherry_blossom:", "🌸"}, {":sparkles:", "✨"},
    {":star:", "⭐"}, {":star2:", "🌟"}, {":dizzy:", "💫"}, {":boom:", "💥"},
    {":fire:", "🔥"}, {":cloud:", "☁️"}, {":sunny:", "☀️"}, {":partly_sunny:", "⛅"},
    {":rainbow:", "🌈"}, {":snowflake:", "❄️"}, {":snowman:", "⛄"},
    {":zap:", "⚡"}, {":ocean:", "🌊"},

    /* Food & Drink */
    {":apple:", "🍎"}, {":green_apple:", "🍏"}, {":pear:", "🍐"}, {":tangerine:", "🍊"},
    {":lemon:", "🍋"}, {":banana:", "🍌"}, {":watermelon:", "🍉"}, {":grapes:", "🍇"},
    {":strawberry:", "🍓"}, {":melon:", "🍈"}, {":cherries:", "🍒"}, {":peach:", "🍑"},
    {":mango:", "🥭"}, {":pineapple:", "🍍"}, {":coconut:", "🥥"}, {":kiwi_fruit:", "🥝"},
    {":tomato:", "🍅"}, {":eggplant:", "🍆"}, {":avocado:", "🥑"}, {":broccoli:", "🥦"},
    {":cucumber:", "🥒"}, {":carrot:", "🥕"}, {":corn:", "🌽"}, {":hot_pepper:", "🌶️"},
    {":potato:", "🥔"}, {":bread:", "🍞"}, {":croissant:", "🥐"}, {":bagel:", "🥯"},
    {":pancakes:", "🥞"}, {":cheese:", "🧀"}, {":meat_on_bone:", "🍖"},
    {":poultry_leg:", "🍗"}, {":bacon:", "🥓"}, {":hamburger:", "🍔"},
    {":fries:", "🍟"}, {":pizza:", "🍕"}, {":hotdog:", "🌭"}, {":taco:", "🌮"},
    {":burrito:", "🌯"}, {":egg:", "🥚"}, {":fried_egg:", "🍳"}, {":shallow_pan_of_food:", "🥘"},
    {":stew:", "🍲"}, {":bowl_with_spoon:", "🥣"}, {":green_salad:", "🥗"},
    {":spaghetti:", "🍝"}, {":ramen:", "🍜"}, {":sushi:", "🍣"}, {":bento:", "🍱"},
    {":curry:", "🍛"}, {":rice_ball:", "🍙"}, {":rice:", "🍚"}, {":ice_cream:", "🍨"},
    {":shaved_ice:", "🍧"}, {":icecream:", "🍦"}, {":doughnut:", "🍩"},
    {":cookie:", "🍪"}, {":birthday:", "🎂"}, {":cake:", "🍰"}, {":cupcake:", "🧁"},
    {":pie:", "🥧"}, {":chocolate_bar:", "🍫"}, {":candy:", "🍬"}, {":lollipop:", "🍭"},
    {":honey_pot:", "🍯"}, {":coffee:", "☕"}, {":tea:", "🍵"}, {":sake:", "🍶"},
    {":beer:", "🍺"}, {":beers:", "🍻"}, {":wine_glass:", "🍷"}, {":cocktail:", "🍸"},
    {":tropical_drink:", "🍹"}, {":champagne:", "🍾"},

    /* Activities */
    {":soccer:", "⚽"}, {":basketball:", "🏀"}, {":football:", "🏈"},
    {":baseball:", "⚾"}, {":tennis:", "🎾"}, {":volleyball:", "🏐"},
    {":8ball:", "🎱"}, {":golf:", "⛳"}, {":trophy:", "🏆"}, {":medal_sports:", "🏅"},
    {":1st_place_medal:", "🥇"}, {":2nd_place_medal:", "🥈"}, {":3rd_place_medal:", "🥉"},
    {":dart:", "🎯"}, {":running:", "🏃"}, {":walking:", "🚶"},
    {":biking:", "🚴"}, {":swimming:", "🏊"}, {":weight_lifting:", "🏋️"},
    {":art:", "🎨"}, {":guitar:", "🎸"}, {":musical_note:", "🎵"},
    {":notes:", "🎶"}, {":microphone:", "🎤"}, {":headphones:", "🎧"},
    {":video_game:", "🎮"}, {":game_die:", "🎲"}, {":bowling:", "🎳"},

    /* Travel & Places */
    {":car:", "🚗"}, {":taxi:", "🚕"}, {":bus:", "🚌"}, {":train:", "🚆"},
    {":bike:", "🚲"}, {":airplane:", "✈️"}, {":rocket:", "🚀"}, {":helicopter:", "🚁"},
    {":ship:", "🚢"}, {":boat:", "⛵"}, {":anchor:", "⚓"}, {":construction:", "🚧"},
    {":fuelpump:", "⛽"}, {":traffic_light:", "🚦"}, {":house:", "🏠"},
    {":house_with_garden:", "🏡"}, {":office:", "🏢"}, {":hospital:", "🏥"},
    {":bank:", "🏦"}, {":hotel:", "🏨"}, {":school:", "🏫"}, {":church:", "⛪"},
    {":fountain:", "⛲"}, {":tent:", "⛺"}, {":park:", "🏞️"}, {":camping:", "🏕️"},
    {":beach_umbrella:", "🏖️"}, {":island:", "🏝️"}, {":mountain:", "⛰️"},
    {":mount_fuji:", "🗻"}, {":volcano:", "🌋"}, {":desert:", "🏜️"},
    {":earth_africa:", "🌍"}, {":earth_americas:", "🌎"}, {":earth_asia:", "🌏"},
    {":globe_with_meridians:", "🌐"}, {":world_map:", "🗺️"},

    /* Objects */
    {":watch:", "⌚"}, {":iphone:", "📱"}, {":calling:", "📲"}, {":computer:", "💻"},
    {":keyboard:", "⌨️"}, {":desktop_computer:", "🖥️"}, {":printer:", "🖨️"},
    {":mouse:", "🖱️"}, {":trackball:", "🖲️"}, {":joystick:", "🕹️"},
    {":camera:", "📷"}, {":camera_flash:", "📸"}, {":video_camera:", "📹"},
    {":tv:", "📺"}, {":radio:", "📻"}, {":telephone_receiver:", "📞"},
    {":phone:", "☎️"}, {":pager:", "📟"}, {":fax:", "📠"}, {":battery:", "🔋"},
    {":electric_plug:", "🔌"}, {":bulb:", "💡"}, {":flashlight:", "🔦"},
    {":candle:", "🕯️"}, {":fire_extinguisher:", "🧯"}, {":wastebasket:", "🗑️"},
    {":money_with_wings:", "💸"}, {":dollar:", "💵"}, {":moneybag:", "💰"},
    {":credit_card:", "💳"}, {":gem:", "💎"}, {":scales:", "⚖️"},
    {":wrench:", "🔧"}, {":hammer:", "🔨"}, {":hammer_and_pick:", "⚒️"},
    {":nut_and_bolt:", "🔩"}, {":gear:", "⚙️"}, {":link:", "🔗"},
    {":lock:", "🔒"}, {":unlock:", "🔓"}, {":key:", "🔑"}, {":door:", "🚪"},
    {":notebook:", "📓"}, {":book:", "📖"}, {":books:", "📚"}, {":newspaper:", "📰"},
    {":bookmark:", "🔖"}, {":label:", "🏷️"}, {":email:", "📧"}, {":envelope:", "✉️"},
    {":incoming_envelope:", "📨"}, {":package:", "📦"}, {":mailbox:", "📫"},
    {":memo:", "📝"}, {":pencil2:", "✏️"}, {":pen:", "🖊️"}, {":paintbrush:", "🖌️"},
    {":crayon:", "🖍️"}, {":paperclip:", "📎"}, {":pushpin:", "📌"},
    {":triangular_ruler:", "📐"}, {":scissors:", "✂️"}, {":file_folder:", "📁"},
    {":open_file_folder:", "📂"}, {":calendar:", "📆"}, {":date:", "📅"},
    {":card_index:", "📇"}, {":chart_with_upwards_trend:", "📈"},
    {":chart_with_downwards_trend:", "📉"}, {":bar_chart:", "📊"},
    {":clipboard:", "📋"}, {":mag:", "🔍"}, {":mag_right:", "🔎"},

    /* Symbols */
    {":100:", "💯"}, {":hash:", "#️⃣"}, {":keycap_star:", "*️⃣"},
    {":zero:", "0️⃣"}, {":one:", "1️⃣"}, {":two:", "2️⃣"}, {":three:", "3️⃣"},
    {":four:", "4️⃣"}, {":five:", "5️⃣"}, {":six:", "6️⃣"}, {":seven:", "7️⃣"},
    {":eight:", "8️⃣"}, {":nine:", "9️⃣"}, {":ten:", "🔟"},
    {":arrow_up:", "⬆️"}, {":arrow_down:", "⬇️"}, {":arrow_left:", "⬅️"},
    {":arrow_right:", "➡️"}, {":arrow_upper_right:", "↗️"}, {":arrow_lower_right:", "↘️"},
    {":arrow_lower_left:", "↙️"}, {":arrow_upper_left:", "↖️"},
    {":arrow_up_down:", "↕️"}, {":left_right_arrow:", "↔️"},
    {":arrows_counterclockwise:", "🔄"}, {":arrow_right_hook:", "↪️"},
    {":leftwards_arrow_with_hook:", "↩️"}, {":arrow_heading_up:", "⤴️"},
    {":arrow_heading_down:", "⤵️"}, {":twisted_rightwards_arrows:", "🔀"},
    {":repeat:", "🔁"}, {":repeat_one:", "🔂"}, {":rewind:", "⏪"},
    {":fast_forward:", "⏩"}, {":play_or_pause_button:", "⏯️"},
    {":arrow_forward:", "▶️"}, {":arrow_backward:", "◀️"},
    {":arrow_double_up:", "⏫"}, {":arrow_double_down:", "⏬"},
    {":pause_button:", "⏸️"}, {":stop_button:", "⏹️"}, {":record_button:", "⏺️"},
    {":musical_note:", "🎵"}, {":notes:", "🎶"}, {":heavy_plus_sign:", "➕"},
    {":heavy_minus_sign:", "➖"}, {":heavy_division_sign:", "➗"},
    {":heavy_multiplication_x:", "✖️"}, {":heavy_dollar_sign:", "💲"},
    {":currency_exchange:", "💱"}, {":tm:", "™️"}, {":copyright:", "©️"},
    {":registered:", "®️"}, {":wavy_dash:", "〰️"}, {":curly_loop:", "➰"},
    {":loop:", "➿"}, {":end:", "🔚"}, {":back:", "🔙"}, {":on:", "🔛"},
    {":top:", "🔝"}, {":soon:", "🔜"}, {":heavy_check_mark:", "✔️"},
    {":ballot_box_with_check:", "☑️"}, {":radio_button:", "🔘"},
    {":white_circle:", "⚪"}, {":black_circle:", "⚫"}, {":red_circle:", "🔴"},
    {":large_blue_circle:", "🔵"}, {":small_orange_diamond:", "🔸"},
    {":small_blue_diamond:", "🔹"}, {":small_red_triangle:", "🔺"},
    {":small_red_triangle_down:", "🔻"}, {":diamond_shape_with_a_dot_inside:", "💠"},
    {":white_square_button:", "🔳"}, {":black_square_button:", "🔲"},
    {":x:", "❌"}, {":o:", "⭕"}, {":warning:", "⚠️"}, {":exclamation:", "❗"},
    {":question:", "❓"}, {":grey_exclamation:", "❕"}, {":grey_question:", "❔"},
    {":bangbang:", "‼️"}, {":interrobang:", "⁉️"}, {":sos:", "🆘"},
    {":no_entry:", "⛔"}, {":no_entry_sign:", "🚫"}, {":name_badge:", "📛"},
    {":no_pedestrians:", "🚷"}, {":children_crossing:", "🚸"},
    {":recycle:", "♻️"}, {":white_check_mark:", "✅"}, {":chart_with_upwards_trend:", "📈"},
    {":sparkle:", "❇️"}, {":eight_spoked_asterisk:", "✳️"},
    {":negative_squared_cross_mark:", "❎"}, {":globe_with_meridians:", "🌐"},
    {":atom_symbol:", "⚛️"}, {":trident:", "🔱"},
    {":checkered_flag:", "🏁"}, {":triangular_flag_on_post:", "🚩"},
    {":crossed_flags:", "🎌"}, {":wave:", "👋"}, {":flag_white:", "🏳️"},
    {":rainbow_flag:", "🏳️‍🌈"},

    /* Additional popular ones */
    {":tada:", "🎉"}, {":confetti_ball:", "🎊"}, {":balloon:", "🎈"},
    {":gift:", "🎁"}, {":ribbon:", "🎀"}, {":crystal_ball:", "🔮"},
    {":hourglass:", "⌛"}, {":alarm_clock:", "⏰"}, {":stopwatch:", "⏱️"},
    {":timer_clock:", "⏲️"}, {":bell:", "🔔"}, {":loudspeaker:", "📢"},
    {":mega:", "📣"}, {":speech_balloon:", "💬"}, {":thought_balloon:", "💭"},
    {":zzz:", "💤"}, {":poop:", "💩"}, {":shit:", "💩"}, {":hankey:", "💩"},
    {":ghost:", "👻"}, {":skull:", "💀"}, {":alien:", "👽"}, {":robot:", "🤖"},
    {":jack_o_lantern:", "🎃"}, {":smiley_cat:", "😺"}, {":smile_cat:", "😸"},
    {":joy_cat:", "😹"}, {":heart_eyes_cat:", "😻"}, {":smirk_cat:", "😼"},
    {":kissing_cat:", "😽"}, {":scream_cat:", "🙀"}, {":crying_cat_face:", "😿"},
    {":pouting_cat:", "😾"},

    {NULL, NULL} /* Sentinel */
};

const char* emoji_find(const char *shortcode);

#endif /* EMOJI_H */
